
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _29_07_19_test.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Books
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Books()
    {

        this.Lending = new HashSet<Lending>();

    }


    public int Id { get; set; }

    public string BookName { get; set; }

    public Nullable<int> BookCount { get; set; }

    public Nullable<double> Price { get; set; }

    public Nullable<int> GenreId { get; set; }

    public bool Deleted { get; set; }



    public virtual BookGenre BookGenre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Lending> Lending { get; set; }

}

}
