
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _29_07_19_test.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Lending
{

    public int Id { get; set; }

    public Nullable<int> BooksId { get; set; }

    public Nullable<int> MembersId { get; set; }

    public Nullable<System.DateTime> DataTimeBorrowed { get; set; }

    public Nullable<int> UsersId { get; set; }

    public string LentedUsername { get; set; }

    public string ReturnedUsername { get; set; }

    public Nullable<decimal> FinedAmount { get; set; }

    public Nullable<System.DateTime> DataTimeReturned { get; set; }



    public virtual Books Books { get; set; }

    public virtual Users Users { get; set; }

    public virtual Members Members { get; set; }

}

}
